# è‡ªåŠ¨å…³é—­é OWNER æˆ– MEMBER åˆ›å»ºçš„ Release æˆ– Pre-release Issue
name: Issue Checker

on:
  issues:
    types: [opened]

jobs:
  release:
    name: check issue
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.author_association != 'MEMBER' && github.event.issue.author_association != 'OWNER') &&
      (
        (github.event.issue.title == 'OpenSumi Pre-Release' && contains(github.event.issue.labels.*.name, 'pre-release')) ||
        (github.event.issue.title == 'OpenSumi Release' && contains(github.event.issue.labels.*.name, 'release'))
      )

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # å…³é—­æœªæˆæƒçš„ç‰ˆæœ¬å‘å¸ƒæµç¨‹
      - name: Close the unauthorized version release process
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.closeandcomment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ğŸ¤– Unauthorized workflow, will be closed now`
            });
