name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    if: github.actor != github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Need more detail
        if: github.event.label.name == 'ğŸ¥¸ needs more detail'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯ (å‚è€ƒ #1165 #1141), æä¾› gif, æˆªå›¾, ä»£ç ç‰‡æ®µ, é…ç½®ä¿¡æ¯, ç‰ˆæœ¬å·, å¯å¤ç°é“¾æ¥ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢! 15 å¤©å†…æœªå›å¤ issue è‡ªåŠ¨å…³é—­ã€‚

            Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to troubleshoot the problem. Please complete the issue description (refer #1165 #1141), provide gifs, screenshots, config, version. And explain the reproduction steps in detail. Thanks so much for your cooperation! The issue will be closed without any replay within 15 days.
    if: github.actor != github.event.issue.user.login
      runs-on: ubuntu-latest
      steps:
        - name: Need reproduce
          if: github.event.label.name == 'ğŸ§ need reproduce'
          uses: actions-cool/issues-helper@main
          with:
            actions: 'create-comment'
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            body: |
              ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·æä¾›ä¸€ä¸ªå¯ä»¥å¤ç°çš„æ¡ˆä¾‹ï¼Œå¯ä»¥é€šè¿‡æˆ‘ä»¬çš„èµ·æ­¥é¡¹ç›® [ide-startup](https://github.com/opensumi/ide-startup) è¿›è¡Œå°è¯•å¤ç°ä½ çš„é—®é¢˜, è°¢è°¢! 15 å¤©å†…æœªå›å¤ issue è‡ªåŠ¨å…³é—­ã€‚

              Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to troubleshoot the problem. Please explain the reproduction steps in detail. Thanks so much for your cooperation! The issue will be closed without any replay within 15 days.
              